services:
  upload:
    build:
      context: .
      dockerfile: ./apps/upload/Dockerfile
      target: development
    command: npm run start upload
    env_file:
      - ./apps/upload/.env
    ports:
      - '3000:3000'
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    command: npm run start gateway
    env_file:
      - ./apps/gateway/.env
    ports:
      - '3004:3004'
  mongo:
    image: mongo
  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
