### Create user
POST /user HTTP/1.1
Host: 192.168.64.5:3001
Content-Type: application/json

{
    "email": "stephen23@yopmail.com",
    "password": "Password@new1"
}

### Login user
POST /auth/login HTTP/1.1
Host: 192.168.64.5:3001
Content-Type: application/json

{
    "email": "stephen23@yopmail.com",
    "password": "Password@new1"
}

### Get user
GET /user HTTP/1.1
Host: 192.168.64.5:3001
Content-Type: application/json