### Login user
POST /auth/login HTTP/1.1
Host: 192.168.64.5:3001
Content-Type: application/json

{
    "email": "stephen24@yopmail.com",
    "password": "Password@new1"
}


#### Uplod file
POST /upload HTTP/1.1
Host: 192.168.64.5:3000
Content-Type: application/json

{
    "fileId": "file_22"
}

### Get all files
GET /upload HTTP/1.1
#Host: localhost:3000
Host: 192.168.64.5:3000
# Cookie: Authentication=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTE2YTFiMmFhYjQyZTM3MThiZTVkYTkiLCJpYXQiOjE2OTYwNzM4ODAsImV4cCI6MTY5NjA3NzQ4MH0.iy8sKQlGEQhw9XIqUdhOO9ficcNVxsYojhEdswZabsw


### Get file by id
GET /upload/651808b0e9ad9aa24e46f87f HTTP/1.1
#Host: localhost:3000
Host: 192.168.64.5:3000
Cookie: Authentication=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTE2YTFiMmFhYjQyZTM3MThiZTVkYTkiLCJpYXQiOjE2OTYwNzM4ODAsImV4cCI6MTY5NjA3NzQ4MH0.iy8sKQlGEQhw9XIqUdhOO9ficcNVxsYojhEdswZabsw


### Update file by id
PATCH /upload/64fe078080cb95b9665682f8 HTTP/1.1
Host: 192.168.64.5:3000
Content-Type: application/json
Cookie: Authentication=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTE2YTFiMmFhYjQyZTM3MThiZTVkYTkiLCJpYXQiOjE2OTYwNzM4ODAsImV4cCI6MTY5NjA3NzQ4MH0.iy8sKQlGEQhw9XIqUdhOO9ficcNVxsYojhEdswZabsw


{
    "fileId": "file_3.4"
}

### Delete file by id
DELETE /upload/64fe078080cb95b9665682f8 HTTP/1.1
Host: 192.168.64.5:3000
Cookie: Authentication=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTE2YTFiMmFhYjQyZTM3MThiZTVkYTkiLCJpYXQiOjE2OTYwNzM4ODAsImV4cCI6MTY5NjA3NzQ4MH0.iy8sKQlGEQhw9XIqUdhOO9ficcNVxsYojhEdswZabsw

