apiVersion: v1
kind: Service
metadata:
  labels:
    app: upload
  name: upload
spec:
  ports:
    - name: 'http'
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: upload
  type: NodePort
