apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - image: meerajahmed/videoshare-gateway:latest
          name: gateway
          env:
            - name: HTTP_PORT
              value: '3004'
            - name: AUTH_GRAPHQL_URL
              value: 'http://auth:3001/graphql'
            - name: UPLOAD_GRAPHQL_URL
              value: 'http://upload:3000/graphql'
            - name: RABBITMQ_URI
              value: 'amqp://rabbitmq:5672'
          ports:
            - containerPort: 3004
