apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway
  name: gateway
spec:
  ports:
    - name: 'http'
      port: 3004
      protocol: TCP
      targetPort: 3004
  selector:
    app: gateway
  type: NodePort
